add sdk section and mention permissionless there
pimlicolabs/erc20-paymaster-contracts pull request #14
Opened 2024-01-30 12:47 UTC by nikmel2803

2024-02-01 19:27 UTC, kristofgazso commented on README.md
> +You can use permissionless.js to interact with an ERC20 Paymaster. Follow [this link](https://docs.pimlico.io/permissionless/tutorial/tutorial-3) to check out tutorial on how to submit user operation
otherwise good to merge!

2024-02-02 00:00 UTC, kristofgazso requested changes

2024-02-02 00:00 UTC, kristofgazso commented on README.md
> +Check out [this docs](https://docs.pimlico.io/permissionless/how-to/paymasters/use-custom-paymaster) if you're going to use custom paymaster implementation.
grammar

2024-02-04 11:54 UTC, kristofgazso commented on README.md
> +Check out [these docs](https://docs.pimlico.io/permissionless/how-to/paymasters/use-custom-paymaster) if you're going to use custom paymaster implementation.
...use _a_ custom paymaster...

2024-02-04 11:56 UTC, nikmel2803 reviewed
article fix

2024-02-05 15:05 UTC, merged